---
apiVersion: v1
kind: Service
metadata:
  name: burrow
  labels:
    app: burrow
spec:
  selector:
    app: burrow
  ports:
  - port: 8000
    name: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: burrow
  labels:
    app: burrow
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: burrow
    spec:
      containers:
      - name: burrow
        image: us.gcr.io/opennms-drift/burrow:test
        imagePullPolicy: Always
        env:
        - name: ZOOKEEPER_HOSTNAME
          value: zk-cs
        - name: ZOOKEEPER_PORT
          value: 2181
        - name: KAFKA_BROKER
          value: kafka-hs
        - name: KAFKA_BROKER_PORT
          value: 9092
        ports:
        - containerPort: 8000
          name: http
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10
