apiVersion: v1
kind: Pod
metadata:
  name: flowgen
spec:
  containers:
  - image: opennms/flowgen
    args:
      - "-i"
      - "30"
      - "-f"
      - "30"
      - "-p"
      - "8877"
      - "172.17.0.23"
    imagePullPolicy: IfNotPresent
    name: flowgen
  restartPolicy: Always
