apiVersion: v1
kind: ReplicationController
metadata:
  name: minion
spec:
  replicas: 1
  selector:
    app: minion
    instance: "{{ instanceId }}"
  template:
    metadata:
      name: minion
      labels:
        app: minion
        instance: "{{ instanceId }}"
    spec:
      containers:
      - name: minion
        image: opennms/minion:latest
        ports:
        - containerPort: 8201
        imagePullPolicy: IfNotPresent
        env:
          - name: OPENNMS_INSTANCE_ID
            value: "{{ instanceId }}"
          - name: USE_KAFKA_SINK
            value: true
        volumeMounts:
        - name: config-overlay-volume
          mountPath: /opt/minion/overlay
      volumes:
        - name: config-overlay-volume
          configMap:
            name: minion-config
