---
apiVersion: v1
kind: Service
metadata:
  name: minion
  labels:
    app: minion
spec:
  ports:
  - port: 8877
    protocol: UDP
    name: netflow-5
  selector:
    app: minion
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: minion
spec:
  replicas: 1
  selector:
    app: minion
    instance: "{{ instanceId }}"
  template:
    metadata:
      name: minion
      labels:
        app: minion
        instance: "{{ instanceId }}"
    spec:
      containers:
      - name: minion
        image: us.gcr.io/opennms-drift/minion:test
        imagePullPolicy: Always
        ports:
        - containerPort: 8201
          name: karaf-shell
        - containerPort: 8877
          protocol: UDP
          name: netflow-5
        env:
          - name: OPENNMS_HTTP_URL
            value: "http://opennms:8980/opennms"
          - name: OPENNMS_BROKER_URL
            value: "failover:tcp://opennms:61616"
          - name: USE_KAFKA_SINK
            value: true
        volumeMounts:
        - name: config-overlay-volume
          mountPath: /opt/minion/overlay
      volumes:
        - name: config-overlay-volume
          configMap:
            name: minion-config
