---
apiVersion: v1
kind: Service
metadata:
  name: opennms
  labels:
    app: opennms
spec:
  ports:
  - port: 8980
    name: web
  - port: 61616
    name: openwire
  selector:
    app: opennms
---
apiVersion: v1
kind: Pod
metadata:
  name: opennms
  labels:
    app: opennms
spec:
  containers:
  - image: us.gcr.io/opennms-drift/opennms:test
    imagePullPolicy: Always
    name: opennms
    resources:
      requests:
        memory: "1Gi"
        cpu: "0.5"
    ports:
    - containerPort: 8980
      name: web
    - containerPort: 8101
      name: karaf-shell
    - containerPort: 61616
      name: openwire
    env:
      - name: POSTGRES_HOST
        value: postgres
      - name: POSTGRES_PORT
        value: 5432
      - name: OPENNMS_DBNAME
        value: opennms
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: postgres
      - name: OPENNMS_DBUSER
        value: opennms
      - name: OPENNMS_DBPASS
        value: opennms
    volumeMounts:
    - name: config-overlay-volume
      mountPath: /opt/opennms/overlay
  volumes:
    - name: config-overlay-volume
      configMap:
        name: opennms-config
        items:
        - key: kafka.properties
          path: opennms.properties.d/kafka.properties
        - key: opennms-activemq.xml
          path: opennms-activemq.xml
        - key: org.opennms.features.flows.persistence.elastic.cfg
          path: org.opennms.features.flows.persistence.elastic.cfg
        - key: org.apache.karaf.features.cfg
          path: org.apache.karaf.features.cfg
        - key: telemetryd-configuration.xml
          path: telemetryd-configuration.xml
  restartPolicy: Always
