---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: udpgen
  labels:
    app: udpgen
spec:
  replicas: 0
  template:
    metadata:
      labels:
        app: udpgen
    spec:
      containers:
      - image: us.gcr.io/opennms-drift/udpgen:test
        imagePullPolicy: Always
        args:
          - "-i"
          - "-x"
          - "netflow5"
          - "-r"
          - "1000"
          - "-h"
          - "minion"
        name: udpgen
      restartPolicy: Always
